name: Merge

on:
  pull_request:
    types:
      - labeled
      - ready_for_review
      - review_request_removed
      - review_requested
      - synchronize
      - unlabeled
  pull_request_review:
    types:
      - dismissed
      - submitted

jobs:
  merge:
    runs-on: ubuntu-latest
    name: Merge
    steps:
    - uses: actions/checkout@v1
    - name: install node v12
        uses: actions/setup-node@v1
        with:
        node-version: 12
    - name: yarn install
        run: yarn install
    - name: tsc
        uses: icrawl/action-tsc@v1
    - name: Integration check
      uses: squalrus/merge-bot@v0.2.0
      with:
        GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
        test: true
        reviewers: true
        labels: ready, merge
        blocking-labels: do not merge
        checks: true
        method: squash
